export interface Allergen {
  id: string;
  name: string;
  icon: string;
  riskLevel: "high" | "medium" | "low";
  description: string;
  safeFoods: string[];
  highRiskFoods: string[];
  crossContaminationRisks: string[];
  symptoms: string[];
  remedies: string[];
}

export const allergens: Allergen[] = [
  {
    id: "peanuts",
    name: "Peanuts",
    icon: "🥜",
    riskLevel: "high",
    description:
      "Peanuts are legumes often used in oils, butters, sauces, and baked goods. Can cause severe reactions.",
    safeFoods: [
      "Fruits",
      "Vegetables",
      "Rice",
      "Poultry",
      "Fish",
      "Sunflower seeds",
      "Sesame oil",
    ],
    highRiskFoods: [
      "Peanut butter",
      "Mixed nuts",
      "Asian cuisines",
      "Baked goods",
      "Chocolate spreads",
      "Granola",
      "Hummus",
    ],
    crossContaminationRisks: [
      "Shared fryers",
      "Bakery trays",
      "Mixed utensils",
      "Processing facilities",
      "Candy/chocolate production lines",
    ],
    symptoms: [
      "Itching in mouth",
      "Throat swelling",
      "Anaphylaxis (severe)",
      "Hives",
      "Breathing difficulty",
    ],
    remedies: [
      "Antihistamine (Benadryl)",
      "Epinephrine if severe",
      "Cool compress",
      "Elevate head",
    ],
  },
  {
    id: "tree-nuts",
    name: "Tree Nuts",
    icon: "🌳",
    riskLevel: "high",
    description:
      "Almonds, walnuts, cashews, pecans. Often found in desserts and nut butters.",
    safeFoods: [
      "Fruits",
      "Vegetables",
      "Legumes",
      "Seeds",
      "Grains",
      "Meat",
      "Fish",
    ],
    highRiskFoods: [
      "Nut butters",
      "Marzipan",
      "Pralines",
      "Cookies",
      "Cereals",
      "Energy bars",
      "Pestos",
    ],
    crossContaminationRisks: [
      "Shared equipment",
      "Bakeries",
      "Candy production",
      "Processor mistakes",
      "Restaurant cross-prep",
    ],
    symptoms: [
      "Mouth itching",
      "Lip swelling",
      "Gastrointestinal upset",
      "Hives",
      "Anaphylaxis",
    ],
    remedies: [
      "Antihistamine",
      "Remove allergen source",
      "Drink water",
      "Monitor breathing",
    ],
  },
  {
    id: "milk",
    name: "Milk",
    icon: "🥛",
    riskLevel: "high",
    description:
      "Cow's milk protein found in dairy products, baked goods, and processed foods.",
    safeFoods: [
      "Fruits",
      "Vegetables",
      "Meat",
      "Fish",
      "Rice",
      "Almond milk",
      "Coconut milk",
    ],
    highRiskFoods: [
      "Cheese",
      "Yogurt",
      "Ice cream",
      "Butter",
      "Cream sauces",
      "Baked goods",
      "Chocolate",
    ],
    crossContaminationRisks: [
      "Shared utensils",
      "Equipment processing",
      "Whey contamination",
      "Hidden dairy additives",
      "Restaurant sauces",
    ],
    symptoms: [
      "Stomach cramps",
      "Diarrhea",
      "Vomiting",
      "Eczema",
      "Respiratory issues",
    ],
    remedies: [
      "Dairy-free alternatives",
      "Probiotics",
      "Ginger tea",
      "ORS solution",
    ],
  },
  {
    id: "eggs",
    name: "Eggs",
    icon: "🥚",
    riskLevel: "high",
    description:
      "Egg proteins found in baked goods, sauces, noodles, and processed foods.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Legumes",
      "Grain breads",
      "Egg-free noodles",
    ],
    highRiskFoods: [
      "Baked goods",
      "Mayonnaise",
      "Pasta",
      "Sauces",
      "Cookies",
      "Ice cream",
      "Custard",
    ],
    crossContaminationRisks: [
      "Bakery equipment",
      "Shared utensils",
      "Egg-based sauces",
      "Industrial processing",
      "Restaurant prep",
    ],
    symptoms: [
      "Hives",
      "Swelling",
      "Stomach pain",
      "Nasal congestion",
      "Anaphylaxis (rare)",
    ],
    remedies: [
      "Antihistamine",
      "Cool compress for itching",
      "Remove allergen",
      "Seek medical help if severe",
    ],
  },
  {
    id: "wheat",
    name: "Wheat",
    icon: "🌾",
    riskLevel: "medium",
    description: "Gluten and wheat proteins in bread, pasta, and cereals.",
    safeFoods: [
      "Rice",
      "Corn",
      "Quinoa",
      "Meat",
      "Fish",
      "Fruits",
      "Vegetables",
    ],
    highRiskFoods: [
      "Bread",
      "Pasta",
      "Cereals",
      "Baked goods",
      "Soy sauce",
      "Beer",
      "Processed foods",
    ],
    crossContaminationRisks: [
      "Flour dust",
      "Shared cutting boards",
      "Toaster use",
      "Processing facilities",
      "Hidden wheat additives",
    ],
    symptoms: [
      "Bloating",
      "Diarrhea",
      "Abdominal pain",
      "Brain fog",
      "Dermatitis",
    ],
    remedies: [
      "Gluten-free diet",
      "Probiotics",
      "Ginger ale",
      "Plenty of water",
    ],
  },
  {
    id: "soy",
    name: "Soy",
    icon: "🌱",
    riskLevel: "medium",
    description: "Soybean proteins in Asian food, oils, and processed items.",
    safeFoods: [
      "Meat",
      "Fish",
      "Fruits",
      "Vegetables",
      "Corn",
      "Rice",
      "Grains",
    ],
    highRiskFoods: [
      "Tofu",
      "Soy sauce",
      "Tempeh",
      "Edamame",
      "Asian noodles",
      "Processed foods",
      "Vegetarian meat",
    ],
    crossContaminationRisks: [
      "Asian restaurants",
      "Shared oils",
      "Processing lines",
      "Hidden soy lecithin",
      "Contaminated utensils",
    ],
    symptoms: [
      "Itching",
      "Swelling of mouth",
      "Stomach upset",
      "Hives",
      "Wheezing",
    ],
    remedies: [
      "Avoid soy products",
      "Check food labels",
      "Antihistamine",
      "Drink water",
    ],
  },
  {
    id: "fish",
    name: "Fish",
    icon: "🐟",
    riskLevel: "high",
    description: "Fish proteins in seafood, sauces, and processed foods.",
    safeFoods: [
      "Meat",
      "Poultry",
      "Vegetables",
      "Fruits",
      "Legumes",
      "Grains",
      "Dairy",
    ],
    highRiskFoods: [
      "Salmon",
      "Tuna",
      "Cod",
      "Fish sauces",
      "Asian cuisines",
      "Processed foods",
      "Worcestershire sauce",
    ],
    crossContaminationRisks: [
      "Seafood markets",
      "Shared fryers",
      "Restaurant prep",
      "Fish-flavored products",
      "Cross-processing",
    ],
    symptoms: [
      "Oral allergy syndrome",
      "Throat swelling",
      "Stomach pain",
      "Hives",
      "Anaphylaxis",
    ],
    remedies: [
      "Epinephrine if severe",
      "Antihistamine",
      "Remove allergen",
      "Elevate head",
    ],
  },
  {
    id: "shellfish",
    name: "Shellfish",
    icon: "🦐",
    riskLevel: "high",
    description: "Shrimp, crab, lobster proteins in seafood dishes.",
    safeFoods: [
      "Meat",
      "Fish",
      "Poultry",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
    ],
    highRiskFoods: [
      "Shrimp",
      "Crab",
      "Lobster",
      "Oysters",
      "Mussels",
      "Thai food",
      "Seafood broths",
    ],
    crossContaminationRisks: [
      "Seafood markets",
      "Shared equipment",
      "Seafood broths",
      "Asian restaurants",
      "Cross-prep areas",
    ],
    symptoms: [
      "Itching of mouth",
      "Throat swelling",
      "Hives",
      "Stomach pain",
      "Anaphylaxis",
    ],
    remedies: [
      "Avoid shellfish",
      "Antihistamine",
      "Epinephrine if needed",
      "Seek medical help",
    ],
  },
  {
    id: "sesame",
    name: "Sesame",
    icon: "🟤",
    riskLevel: "medium",
    description:
      "Sesame seeds in oils, tahini, and Middle Eastern/Asian foods.",
    safeFoods: [
      "Meat",
      "Vegetables",
      "Fruits",
      "Rice",
      "Corn",
      "Potatoes",
      "Legumes",
    ],
    highRiskFoods: [
      "Tahini",
      "Hummus",
      "Halva",
      "Asian noodles",
      "Middle Eastern dishes",
      "Tahini paste",
      "Granola",
    ],
    crossContaminationRisks: [
      "Shared equipment",
      "Tahini processing",
      "Restaurant oils",
      "Bakery products",
      "Spice mixes",
    ],
    symptoms: [
      "Mouth itching",
      "Swelling",
      "Hives",
      "Gastrointestinal upset",
      "Anaphylaxis",
    ],
    remedies: [
      "Antihistamine",
      "Remove allergen",
      "Ice water",
      "Monitor symptoms",
    ],
  },
  {
    id: "mustard",
    name: "Mustard",
    icon: "💛",
    riskLevel: "medium",
    description: "Mustard seeds in condiments, sauces, and prepared foods.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Mustard condiment",
      "Vinaigrettes",
      "Mayonnaise",
      "Prepared sauces",
      "Dressings",
      "Spice blends",
      "Asian sauces",
    ],
    crossContaminationRisks: [
      "Shared condiment containers",
      "Restaurant prep",
      "Processing facilities",
      "Spice mixes",
      "Sauce production",
    ],
    symptoms: [
      "Oral allergy syndrome",
      "Stomach upset",
      "Hives",
      "Swelling",
      "Eczema flare",
    ],
    remedies: [
      "Check food labels",
      "Antihistamine",
      "Ginger tea",
      "Avoid triggers",
    ],
  },
  {
    id: "celery",
    name: "Celery",
    icon: "🥬",
    riskLevel: "low",
    description: "Celery vegetables and celery seed in soups and seasonings.",
    safeFoods: [
      "Meat",
      "Fish",
      "Fruits",
      "Grains",
      "Legumes",
      "Most vegetables",
      "Dairy",
    ],
    highRiskFoods: [
      "Celery vegetable",
      "Soups",
      "Broths",
      "Spice blends",
      "Some seasonings",
      "Pickles",
      "Cured meats",
    ],
    crossContaminationRisks: [
      "Shared cutting boards",
      "Broth preparation",
      "Spice mixes",
      "Restaurant prep",
      "Processed seasonings",
    ],
    symptoms: [
      "Oral allergy syndrome",
      "Lip swelling",
      "Throat itching",
      "Stomach upset",
      "Dermatitis",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Avoid fresh celery",
      "Check processed foods",
    ],
  },
  {
    id: "sulfites",
    name: "Sulfites",
    icon: "🍷",
    riskLevel: "medium",
    description:
      "Preservatives in wine, dried fruits, processed foods, and beverages.",
    safeFoods: [
      "Fresh meat",
      "Fresh fish",
      "Fresh vegetables",
      "Fresh fruits",
      "Rice",
      "Grains",
    ],
    highRiskFoods: [
      "Wine",
      "Beer",
      "Dried fruits",
      "Processed foods",
      "Pickled foods",
      "Juices",
      "Sauces",
    ],
    crossContaminationRisks: [
      "Sulfite processing",
      "Industrial preservation",
      "Cross-processing",
      "Restaurant foods",
      "Dried food handling",
    ],
    symptoms: [
      "Asthma triggers",
      "Hives",
      "Stomach upset",
      "Itching",
      "Swelling",
    ],
    remedies: [
      "Avoid sulfite foods",
      "Antihistamine",
      "Bronchodilator if asthma",
      "Drink water",
    ],
  },
  {
    id: "lupin",
    name: "Lupin",
    icon: "🌼",
    riskLevel: "low",
    description: "Lupin beans used in flour and vegetarian products.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Rice",
      "Dairy",
    ],
    highRiskFoods: [
      "Lupin flour",
      "Vegetarian burgers",
      "Pasta",
      "Baked goods",
      "Processed vegetarian items",
      "Plant-based proteins",
      "Specialty flours",
    ],
    crossContaminationRisks: [
      "Flour processing",
      "Bakery equipment",
      "Plant-based product lines",
      "Grain mills",
      "Processing facilities",
    ],
    symptoms: [
      "Cross-reaction with peanuts",
      "Oral allergy",
      "Hives",
      "Swelling",
      "Gastrointestinal upset",
    ],
    remedies: [
      "Avoid lupin products",
      "Antihistamine",
      "Monitor peanut allergy",
      "Check labels",
    ],
  },
  {
    id: "mollusks",
    name: "Mollusks",
    icon: "🦪",
    riskLevel: "high",
    description: "Squid, octopus, snails, mussels in seafood dishes.",
    safeFoods: [
      "Meat",
      "Fish",
      "Poultry",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
    ],
    highRiskFoods: [
      "Squid",
      "Octopus",
      "Snails",
      "Mussels",
      "Clams",
      "Scallops",
      "Seafood broths",
    ],
    crossContaminationRisks: [
      "Seafood markets",
      "Shared fryers",
      "Restaurant prep",
      "Cross-processing",
      "Seafood facilities",
    ],
    symptoms: [
      "Throat swelling",
      "Hives",
      "Stomach pain",
      "Anaphylaxis",
      "Wheezing",
    ],
    remedies: [
      "Epinephrine if severe",
      "Antihistamine",
      "Remove allergen",
      "Seek medical help",
    ],
  },
  {
    id: "sesame-seeds",
    name: "Sesame Seeds",
    icon: "⚪",
    riskLevel: "medium",
    description: "Whole sesame seeds in various cuisines.",
    safeFoods: [
      "Meat",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Rice",
      "Dairy",
    ],
    highRiskFoods: [
      "Bagels",
      "Breads",
      "Asian noodles",
      "Tahini",
      "Salad dressings",
      "Granola",
      "Halva",
    ],
    crossContaminationRisks: [
      "Bakery equipment",
      "Shared utensils",
      "Spice mixes",
      "Processing lines",
      "Restaurant prep",
    ],
    symptoms: [
      "Oral allergy",
      "Throat itching",
      "Hives",
      "Swelling",
      "Anaphylaxis",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Avoid seeds",
      "Check labels",
    ],
  },
  {
    id: "sulfur-dioxide",
    name: "Sulfur Dioxide",
    icon: "🔧",
    riskLevel: "medium",
    description: "Food preservative in dried fruits and beverages.",
    safeFoods: [
      "Fresh foods",
      "Unpreserved items",
      "Freshly cooked meals",
      "Organic foods",
      "Home-prepared foods",
    ],
    highRiskFoods: [
      "Dried fruits",
      "Wine",
      "Processed foods",
      "Fruit juices",
      "Pickled items",
      "Canned foods",
      "Condiments",
    ],
    crossContaminationRisks: [
      "Industrial processing",
      "Food preservation lines",
      "Canning facilities",
      "Beverage production",
      "Cross-processing",
    ],
    symptoms: [
      "Asthma attacks",
      "Hives",
      "Stomach upset",
      "Swelling",
      "Itching",
    ],
    remedies: [
      "Avoid preserved foods",
      "Eat fresh items",
      "Bronchodilator if needed",
      "Antihistamine",
    ],
  },
  {
    id: "mustard-seed",
    name: "Mustard Seed",
    icon: "🌰",
    riskLevel: "medium",
    description: "Mustard seed in condiments and seasonings.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Mustard",
      "Sauces",
      "Dressings",
      "Spice blends",
      "Prepared foods",
      "Pickles",
      "Vinaigrettes",
    ],
    crossContaminationRisks: [
      "Shared condiment containers",
      "Spice mills",
      "Restaurant prep",
      "Processing facilities",
      "Sauce production",
    ],
    symptoms: [
      "Stomach upset",
      "Hives",
      "Swelling",
      "Itching",
      "Dermatitis",
    ],
    remedies: [
      "Check labels",
      "Antihistamine",
      "Avoid mustard",
      "Ice water",
    ],
  },
  {
    id: "almonds",
    name: "Almonds",
    icon: "🟫",
    riskLevel: "high",
    description: "Almond nuts and almond milk/products.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Almond milk",
      "Almond butter",
      "Marzipan",
      "Baked goods",
      "Chocolate",
      "Energy bars",
      "Granola",
    ],
    crossContaminationRisks: [
      "Tree nut facilities",
      "Bakery equipment",
      "Food processing",
      "Candy production",
      "Shared fryers",
    ],
    symptoms: [
      "Oral allergy",
      "Throat itching",
      "Hives",
      "Swelling",
      "Anaphylaxis",
    ],
    remedies: [
      "Antihistamine",
      "Epinephrine if severe",
      "Ice water",
      "Remove allergen",
    ],
  },
  {
    id: "walnuts",
    name: "Walnuts",
    icon: "🌳",
    riskLevel: "high",
    description: "Walnut nuts in baked goods and nut butters.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Walnut butter",
      "Baked goods",
      "Salads",
      "Cookies",
      "Granola",
      "Cereals",
      "Energy bars",
    ],
    crossContaminationRisks: [
      "Tree nut processing",
      "Bakery equipment",
      "Shared utensils",
      "Candy production",
      "Industrial mixing",
    ],
    symptoms: [
      "Mouth itching",
      "Throat swelling",
      "Hives",
      "Anaphylaxis",
      "Swelling",
    ],
    remedies: [
      "Antihistamine",
      "Epinephrine if needed",
      "Remove allergen",
      "Ice water",
    ],
  },
  {
    id: "cashews",
    name: "Cashews",
    icon: "🥔",
    riskLevel: "high",
    description: "Cashew nuts in nut butters, baked goods, and sauces.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Cashew butter",
      "Asian sauces",
      "Baked goods",
      "Cookies",
      "Energy bars",
      "Candies",
      "Granola",
    ],
    crossContaminationRisks: [
      "Tree nut facilities",
      "Bakery equipment",
      "Asian restaurants",
      "Shared equipment",
      "Food processing",
    ],
    symptoms: [
      "Severe reactions common",
      "Anaphylaxis",
      "Throat swelling",
      "Hives",
      "Oral allergy",
    ],
    remedies: [
      "Epinephrine",
      "Antihistamine",
      "Seek medical help",
      "Emergency services",
    ],
  },
  {
    id: "pecans",
    name: "Pecans",
    icon: "🌙",
    riskLevel: "high",
    description: "Pecan nuts in desserts and pastries.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Pecan pie",
      "Baked goods",
      "Candies",
      "Granola",
      "Cookies",
      "Energy bars",
      "Pralines",
    ],
    crossContaminationRisks: [
      "Bakery equipment",
      "Tree nut facilities",
      "Candy production",
      "Shared utensils",
      "Food processing",
    ],
    symptoms: [
      "Oral allergy",
      "Throat itching",
      "Hives",
      "Swelling",
      "Anaphylaxis",
    ],
    remedies: [
      "Antihistamine",
      "Epinephrine if severe",
      "Remove allergen",
      "Ice water",
    ],
  },
  {
    id: "pistachios",
    name: "Pistachios",
    icon: "💚",
    riskLevel: "high",
    description: "Pistachio nuts in snacks and desserts.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Pistachio nuts",
      "Pistachio ice cream",
      "Candies",
      "Baked goods",
      "Energy bars",
      "Salads",
      "Granola",
    ],
    crossContaminationRisks: [
      "Tree nut processing",
      "Bakery equipment",
      "Candy production",
      "Shared equipment",
      "Ice cream facilities",
    ],
    symptoms: [
      "Oral allergy",
      "Throat swelling",
      "Hives",
      "Swelling",
      "Anaphylaxis",
    ],
    remedies: [
      "Antihistamine",
      "Epinephrine if needed",
      "Remove allergen",
      "Ice water",
    ],
  },
  {
    id: "chickpeas",
    name: "Chickpeas",
    icon: "🟢",
    riskLevel: "low",
    description: "Chickpeas in hummus, curries, and salads.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Dairy",
      "Most legumes",
    ],
    highRiskFoods: [
      "Hummus",
      "Falafel",
      "Curries",
      "Salads",
      "Processed foods",
      "Flours",
      "Pasta",
    ],
    crossContaminationRisks: [
      "Legume processing",
      "Restaurant prep",
      "Spice contamination",
      "Shared equipment",
      "Food preparation areas",
    ],
    symptoms: [
      "Bloating",
      "Gas",
      "Stomach upset",
      "Rashes",
      "Oral allergy",
    ],
    remedies: [
      "Digestive enzymes",
      "Probiotics",
      "Ginger tea",
      "Plenty of water",
    ],
  },
  {
    id: "lentils",
    name: "Lentils",
    icon: "🟠",
    riskLevel: "low",
    description: "Lentils in curries, soups, and salads.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Dairy",
      "Most legumes",
    ],
    highRiskFoods: [
      "Lentil soup",
      "Curries",
      "Dal",
      "Salads",
      "Processed lentil products",
      "Flour",
      "Pasta",
    ],
    crossContaminationRisks: [
      "Spice contamination",
      "Legume processing",
      "Restaurant prep",
      "Shared equipment",
      "Grain mills",
    ],
    symptoms: [
      "Bloating",
      "Gas",
      "Stomach pain",
      "Rashes",
      "Itching",
    ],
    remedies: [
      "Probiotic foods",
      "Digestive enzymes",
      "Ginger",
      "Fennel tea",
    ],
  },
  {
    id: "peas",
    name: "Peas",
    icon: "💚",
    riskLevel: "low",
    description: "Green peas and pea products.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Dairy",
      "Most legumes",
    ],
    highRiskFoods: [
      "Green peas",
      "Pea soup",
      "Pea flour",
      "Processed pea products",
      "Some pasta",
      "Plant-based proteins",
      "Salads",
    ],
    crossContaminationRisks: [
      "Legume processing",
      "Restaurant prep",
      "Spice contamination",
      "Shared equipment",
      "Food facilities",
    ],
    symptoms: [
      "Bloating",
      "Gas",
      "Stomach upset",
      "Oral allergy",
      "Rashes",
    ],
    remedies: [
      "Probiotics",
      "Digestive enzymes",
      "Ginger tea",
      "Water",
    ],
  },
  {
    id: "coconut",
    name: "Coconut",
    icon: "🥥",
    riskLevel: "low",
    description: "Coconut products in curries, desserts, and beverages.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Coconut milk",
      "Coconut oil",
      "Shredded coconut",
      "Curries",
      "Desserts",
      "Candies",
      "Chocolate",
    ],
    crossContaminationRisks: [
      "Coconut processing",
      "Industrial kitchens",
      "Bakery equipment",
      "Candy production",
      "Restaurant prep",
    ],
    symptoms: [
      "Oral allergy",
      "Swelling",
      "Hives",
      "Stomach upset",
      "Anaphylaxis (rare)",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Remove allergen",
      "Monitor symptoms",
    ],
  },
  {
    id: "mushrooms",
    name: "Mushrooms",
    icon: "🍄",
    riskLevel: "low",
    description: "Various mushroom varieties in soups and dishes.",
    safeFoods: [
      "Meat",
      "Fish",
      "Vegetables (non-fungal)",
      "Fruits",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Mushroom soup",
      "Cooked mushrooms",
      "Mushroom sauces",
      "Pizza toppings",
      "Asian dishes",
      "Processed foods",
      "Marinades",
    ],
    crossContaminationRisks: [
      "Restaurant prep",
      "Shared cutting boards",
      "Kitchen utensils",
      "Food processing",
      "Spice contamination",
    ],
    symptoms: [
      "Oral allergy",
      "Itching mouth",
      "Throat swelling",
      "Stomach upset",
      "Rashes",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Avoid mushrooms",
      "Check menus carefully",
    ],
  },
  {
    id: "mango",
    name: "Mango",
    icon: "🥭",
    riskLevel: "low",
    description: "Mango fruit in beverages, desserts, and salads.",
    safeFoods: [
      "Most fruits",
      "Vegetables",
      "Meat",
      "Fish",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Fresh mango",
      "Mango juice",
      "Mango lassi",
      "Mango desserts",
      "Mango pickle",
      "Chutneys",
      "Candies",
    ],
    crossContaminationRisks: [
      "Cross-reaction with cashew",
      "Restaurant prep",
      "Juice processing",
      "Fruit handling areas",
      "Dessert preparation",
    ],
    symptoms: [
      "Oral allergy syndrome",
      "Lip swelling",
      "Throat itching",
      "Stomach upset",
      "Dermatitis (from skin)",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Cook mango (reduces symptoms)",
      "Avoid raw mango",
    ],
  },
  {
    id: "strawberries",
    name: "Strawberries",
    icon: "🍓",
    riskLevel: "low",
    description: "Strawberry fruit in desserts and beverages.",
    safeFoods: [
      "Most fruits",
      "Vegetables",
      "Meat",
      "Fish",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Fresh strawberries",
      "Strawberry jam",
      "Desserts",
      "Ice cream",
      "Yogurt",
      "Smoothies",
      "Candies",
    ],
    crossContaminationRisks: [
      "Bakery equipment",
      "Dessert preparation",
      "Ice cream facilities",
      "Jam production",
      "Restaurant prep",
    ],
    symptoms: [
      "Oral allergy",
      "Itching mouth",
      "Hives",
      "Swelling",
      "Stomach upset",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Avoid strawberries",
      "Eat in moderation",
    ],
  },
  {
    id: "kiwi",
    name: "Kiwi",
    icon: "🥝",
    riskLevel: "low",
    description: "Kiwi fruit in smoothies and desserts.",
    safeFoods: [
      "Most fruits",
      "Vegetables",
      "Meat",
      "Fish",
      "Grains",
      "Legumes",
      "Dairy",
    ],
    highRiskFoods: [
      "Fresh kiwi",
      "Kiwi juice",
      "Smoothies",
      "Desserts",
      "Fruit salads",
      "Jams",
      "Candies",
    ],
    crossContaminationRisks: [
      "Fruit processing",
      "Restaurant prep",
      "Juice facilities",
      "Dessert production",
      "Shared preparation areas",
    ],
    symptoms: [
      "Oral allergy syndrome",
      "Lip and mouth swelling",
      "Throat itching",
      "Stomach upset",
      "Hives",
    ],
    remedies: [
      "Antihistamine",
      "Ice water",
      "Avoid kiwi",
      "Cook if possible",
    ],
  },
];

export const highRiskAllergens = allergens.filter((a) => a.riskLevel === "high");
export const commonAllergens = [
  "peanuts",
  "tree-nuts",
  "milk",
  "eggs",
  "wheat",
  "soy",
  "fish",
  "shellfish",
];
